version: '3.8'

services:
  tv-masjid:
    build: .
    container_name: tv-masjid-app
    restart: unless-stopped
    ports:
      - "8088:80" # <-- Nah, ini diganti jadi 8088
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./config.json:/var/www/html/config.json